apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-$($vars.namespace)
  namespace: $($vars.namespace)
  annotations:
    kubernetes.io/ingress.class: "nginx"
  
spec:

  tls:

    - hosts:
      - example.com
      secretName: cert-example-com


  rules:

  - host: example.com
    http:
      paths:
      - backend:
          serviceName: example-app
          servicePort: 80
        path: /