kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: $($vars.name)
  namespace: $($vars.namespace)
provisioner: ebs.csi.aws.com
parameters:
  type: $($vars.type)
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain