apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-$($vars.name)
  namespace: $($vars.namespace)
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: $($vars.storageClass)
  resources:
    requests:
      storage: $($vars.sizeGb)Gi