apiVersion: v1
kind: Service
metadata:
  name: $($vars.name)
  namespace: $($vars.namespace)
spec:
  selector:
    app: $($vars.name)
  ports:
  - port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $($vars.name)
  namespace: $($vars.namespace)
  labels:
    app: $($vars.name)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $($vars.name)
  template:
    metadata:
      labels:
        app: $($vars.name)
    spec:
      containers:
      - name: $($vars.name)
        image: $($config.ContainerRegistry)/$($vars.imageName):0.0
        env:
        - name: SOME_VAR
          value: "some value"
        ports:
        - containerPort: 80